sudo: required
language: node_js
node_js:
  - node
scripts:
  - npm install
  - npm install codecov -g
  - npm run test-ci
  - npm run build-ci
  - codecov -f coverage/*.json
after_success:,
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)
