sudo: required
language: node_js
node_js:
  - node
script:
  - npm install
  - npm install codecov -g
  - npm run test-ci
  - npm run build-ci
  - codecov -f coverage/*.json
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

sudo: required
language: node
node_js:
  - node
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
scripts:
  - npm install
  - npm install codecov -g
  - npm run vscode:prepublish
  - npm run test-ci
  - npm run build-ci
after_success:
  - bash <(curl -s https://codecov.io/bash)


